apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-react-depl
spec:
  selector:
    matchLabels:
      app: mon-app-react
  replicas: 1
  template:
    metadata:
      labels:
        app: mon-app-react
    spec:
      containers:
        - name: mon-app-react
          image: mon-app-react/mon-app-react:latest
